# Generated by Django 4.1.8 on 2023-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_views', '0002_individualoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualoptions',
            name='show_neighbors',
            field=models.BooleanField(default=False),
        ),
    ]
