# Generated by Django 4.2.10 on 2024-03-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_views', '0006_powerpanelcoordinate_powerfeedcoordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualoptions',
            name='group_locations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualoptions',
            name='group_racks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualoptions',
            name='group_sites',
            field=models.BooleanField(default=False),
        ),
    ]
