# Generated by Django 4.2.10 on 2024-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_views', '0007_individualoptions_group_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualoptions',
            name='straight_cables',
            field=models.BooleanField(default=False),
        ),
    ]