# Generated by Django 5.0.6 on 2024-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_views', '0008_straight_cables'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualoptions',
            name='group_virtualchassis',
            field=models.BooleanField(default=False),
        ),
    ]
