# Generated by Django 5.2.9 on 2026-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_views', '0011_individualoptions_node_label_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualoptions',
            name='draw_termination_labels',
            field=models.BooleanField(default=False),
        ),
    ]
