# Generated by Django 5.2.12 on 2026-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_views', '0012_individualoptions_draw_termination_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualoptions',
            name='draw_cable_labels',
            field=models.BooleanField(default=False),
        ),
    ]
